* ML 알고리즘을 적용하기 전 데이터에 대해 미리 처리해야 할 기본 사항이 있음
    1. **결측치(NaN, Null 값)은 허용되지 않음**. Null값은 고정된 다른 값으로 변환해야 함
        * Null 값이 적은 경우: 피처의 평균값 등으로 대체 가능
        * Null 값이 대부분인 경우: 해당 피처를 드롭
    2. **문자열 값을 입력 값으로 허용하지 않음**. 모든 문자열은 인코딩왜서 숫자 형으로 변화해야 함
        * 문자열 피처는 카테고리형 피처와 텍스트형 피처를 의미
        * 카테고리형 피처는 코드 값으로 표현하는 게 더 이해하기 쉬울 것
        * 텍스트형 피처는 피처 벡터화등의 기법으로 벡터화하거나 불필요한 피처라고 판단되면 삭제하는 것이 좋음
        * 식별자 피처는 단순히 데이터 로우를 식별하는 용도로 사용되기 때문에 예측에 중요한 요소가 될 수 없으며 알고리즘을 복잡하게 만들고 예측 성능을 떨어뜨리기 때문
    

## 1. 데이터 인코딩

### 1.1 레이블 인코딩(Label encoding)
* 레이블 인코딩은 LabelEncoder 클래스로 구현
* LabelEncoder를 객체로 생성한 후 `fit()`과 `transform()`을 호출해 레이블 인코딩을 수행

In [2]:
from sklearn.preprocessing import LabelEncoder

items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

# LabelEncoder를 객체로 생성한 후 , fit( ) 과 transform( ) 으로 label 인코딩 수행. 
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값:',labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


* 문자열 값이 어떤 숫자 값으로 인코딩됐는지 알기 위해서는 LabelEncoder 객체의 `classes_` 속성값으로 확인
    * `classes_` 속성은 0번부터 순서대로 변환된 인코딩 값에 대한 원본값을 가지고 있음

In [2]:
print('인코딩 클래스:',encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


* `inverse_transform()`을 통해 인코딩된 값을 다시 디코딩할 수 있음

In [3]:
print('디코딩 원본 값:',encoder.inverse_transform([4, 5, 2, 0, 1, 1, 3, 3]))

디코딩 원본 값: ['전자렌지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


C:\Users\chkwon\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


**레이블 인코딩 정리**
* 레이블 인코딩은 간단하게 문자열 값을 숫자형 카테고리 값으로 변환
* 레이블 인코딩이 일괄적인 숫자 값으로 변환이 되면서 몇몇 ML 알고리즘에 적용할 경우 예측 성능이 떨어지는 경우가 발생할 수 있음
    * 이유: 숫자 값의 경우 크고 작음에 대한 특성이 작용하기 때문
* 문장열의 숫자 변환 값은 단순 코드이므로 숫자 값에 따른 순서나 중요도로 인식돼서는 안됨
* 레이블 인코딩은 선형회귀와 같은 ML 알고리즘에는 적용하면 안됨. 트리 계열의 ML 알고리즘은 숫자의 특성을 반영하지 않으므로 레이블 인코딩도 별문제 없음

### 1.2 원-핫 인코딩(One-Hot encoding)
* 레이블 인코딩의 문제점을 해결하기 위한 인코딩 방식
* 피처 값의 유형에 따라 새로운 피처를 추가해 고유 값에 해당하는 칼럼에만 1을 표시하고 나머지 칼럼에는 0을 표시하는 방식
* 행 형태로 돼 있는 피처의 고유 값을 열 형태로 차원을 변환한 뒤, 고유 값에 해당하는 칼럼에만 1을 표시하고 나머지 칼럼에는 0을 표시

* 레이블 인코딩 예제를 참조하면 TV가 0, 냉장고 1, 믹서 2, 선풍기 3, 전자레인지 4, 컴퓨터가 5로 인코딩돼 있음
* 0부터 5까지 6개의 상품 분류 고유 값에 따라 상품 분류 피처를 6개의 상품 분류 고유 값 피처로 변환
    * 해당 레코드의 상품 분류가 TV인 경우 상품 분류_TV 피처에만 1을 입력하고, 나머지 피처는 모두 0
* 해당 고유 값에 매칭되는 피처만 1이고 나머지 피처는 0을 입력

* 원-핫 인코딩은 사이킷런에서 OneHotEncoder 클래스로 쉽게 변환 가능
* 주의할 점
    1. OneHotEcoder로 변환하기 전에 모든 문자열 값이 숫자형 값으로 변환돼야 함
    2. 입력 값으로 2차원 데이터가 필요

* 8개의 레코드와 1개의 칼럼을 가진 원본 데이터가 8개의 레코드와 6개의 칼럼을 가진 데이터로 변환됨

In [4]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

# 먼저 숫자값으로 변환을 위해 LabelEncoder로 변환합니다. 
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print(labels)
# 2차원 데이터로 변환합니다.
labels = labels.reshape(-1,1) # reshape(-1, 1): 해당 열 개수만큼 자동으로 변환됨

# 원-핫 인코딩을 적용합니다. 
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

[0 1 4 5 3 3 2 2]
원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


C:\Users\slc\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


* 판다스에는 원-핫 인코딩을 더 쉽게 지원하는 API가 있음
* `get_dummies()`를 이용. 사이킷런의 OneHotEncoder와 다르게 문자열 카테고리 값을 숫자 형으로 변환할 필요 없이 바로 변환할 수 있음

In [6]:
import pandas as pd

df = pd.DataFrame({'item':['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서'] })
print(df)
print(pd.get_dummies(df))

   item
0    TV
1   냉장고
2  전자렌지
3   컴퓨터
4   선풍기
5   선풍기
6    믹서
7    믹서
   item_TV  item_냉장고  item_믹서  item_선풍기  item_전자렌지  item_컴퓨터
0        1         0        0         0          0         0
1        0         1        0         0          0         0
2        0         0        0         0          1         0
3        0         0        0         0          0         1
4        0         0        0         1          0         0
5        0         0        0         1          0         0
6        0         0        1         0          0         0
7        0         0        1         0          0         0


## 2. 피처 스케일링과 정규화
* 피처 스케일링: 서로 다른 변수의 값 범위를 일정한 수준으로 맞추는 작업. 표준화와 정규화가 있음


1. **표준화**: 데이터의 피처 각각 이 평균이 0이고 분산이 1인 가우시안 정규 분포를 가진 값으로 변환하는 것
    * 표준화를 통해 변환될 피처 $x$의 새로운 i번째 데이터를 $x_inew$라고 한다면 이 값은 원래 값에서 피처 $x$의 평균을 뺀 값을 피처 $x$의 표준편차로 나눈 값으로 계산할 수 있음
    
2. **정규화**: 서로 다른 피처의 크기를 통일하기 위해 크기를 변환
    * 개별 데이터의 크기를 모두 똑같은 단위로 변경하는 것
    * 새로운 데이터 $x_inew$는 원래 값에서 피처 $x$의 최솟값을 뺀 값을 피처 $x$의 최댓값과 최솟값의 차이로 나눈 값으로 변환할 수 있음

* 사이킷런의 전처리에서 제공하는 Normalizer 모듈과 일반적인 정규화는 차이가 있음. 사이킷런의 Normalizer 모듈은 선형대수에서의 정규화 개념이 적용됐으며, 개별 벡터의 크기를 맞추기 위해 변환하는 것을 의미
    * 개별 벡터를 모든 피처 벡터의 크기로 나눠줌

### 2.1 StandardScaler
* 개별 피처를 평균이 0이고, 분산이 1인 값으로 변환해줌
* 사이킷런에서 구현한 RBF 커널을 이용하는 서포트 벡터 머신이나 선형 회귀, 로지스틱 회귀는 데이터가 가우시안 분포를 가지고 있다고 가정하고 구현됐기 때문에 사전에 표준화를 적용하는 것은 예측 성능 향상에 중요한 요소가 될 수 있음

In [8]:
from sklearn.datasets import load_iris
import pandas as pd
# 붓꽃 데이터 셋을 로딩하고 DataFrame으로 변환합니다. 
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print('feature 들의 평균 값')
print(iris_df.mean())
print('\nfeature 들의 분산 값')
print(iris_df.var())


feature 들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature 들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


* StandardScaler 객체를 생성한 후 `fit()`과 `transform()` 메서드에 변환대상 피처 데이터 세트를 입력하고 호출하면 변환됨
    * `transform()`을 호출할 때 스케일 변환된 데이터 세트가 넘파이의 ndarray이므로 이를 DataFrame으로 변환해 평균값과 분산 값을 다시 확인

In [7]:
from sklearn.preprocessing import StandardScaler

# StandardScaler객체 생성
scaler = StandardScaler()
# StandardScaler 로 데이터 셋 변환. fit( ) 과 transform( ) 호출.  
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

#transform( )시 scale 변환된 데이터 셋이 numpy ndarry로 반환되어 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature 들의 평균 값')
print(iris_df_scaled.mean())
print('\nfeature 들의 분산 값')
print(iris_df_scaled.var())

feature 들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.637024e-15
petal length (cm)   -1.482518e-15
petal width (cm)    -1.623146e-15
dtype: float64

feature 들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


* 모든 칼럼 값의 평균이 0에 아주 가까운 값으로, 분산은 1에 아주 가까운 값으로 변환됐음

### 2.2 MinMaxScaler
* MinMaxScaler는 데이터값을 0과 1 사이의 범위 값으로 변환(음수 값이 있다면 -1에서 1값으로 변환)

* 데이터의 분포가 가우시안 분포가 아닐 경우에 Min, Max Scale을 적용
    * 모든 피처에 0에서 1 사이의 값으로 변환되는 스케일링이 적용됐음을 알 수 있음

In [9]:
from sklearn.preprocessing import MinMaxScaler

# MinMaxScaler객체 생성
scaler = MinMaxScaler()
# MinMaxScaler 로 데이터 셋 변환. fit() 과 transform() 호출.  
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform()시 scale 변환된 데이터 셋이 numpy ndarry로 반환되어 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature들의 최소 값')
print(iris_df_scaled.min())
print('\nfeature들의 최대 값')
print(iris_df_scaled.max())


feature들의 최소 값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature들의 최대 값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


## 3. 학습 데이터와 테스트 데이터의 스케일링 변환 시 유의점
* Scaler를 객체를 이용해 데이터의 스케일링 변환 시 `fit()`, `transform()`, `fit_transform()` 메소드를 이용
    * `fit()`: 데이터 변환을 위한 기준 정보 설정(데이터 세트의 최댓값/최솟값 설정 등)을 적용
    * `transform()`: 설정된 정보를 이용해 데이터를 변환
    * `fit_transform()`: `fit()` + `transform()`

* `fit()`, `transform()`을 적용할 때 주의할 점
    *  Scaler 객체를 이용해 학습 데이터 세트로 `fit()`과 `transform()`을 적용하면 테스트 데이터 세트로는 다시 `fit()`을 수행하지 않고 학습 데이터 세트로 `fit()`을 수행한 결과를 이용해 `transform()` 변환을 적용해야함
    * 학습 데이터로 `fit()`이 적용된 스케일링 기준 정보를 그대로 테스트 데이터에 적용해야 함. 그렇지 않고 테스트 데이터로 다시 새로운 스케일링 기준 정보를 만들게 되면 학습 데이터와 테스트 데이터의 스케일링 기준 정보가 서로 달라지기 때문에 올바른 예측 결과를 도출하지 못함

**테스트 데이터에 `fit()`을 적용할 때 발생하는 문제 확인**

In [11]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# 학습 데이터는 0 부터 10까지, 테스트 데이터는 0 부터 5까지 값을 가지는 데이터 세트로 생성
# Scaler클래스의 fit(), transform()은 2차원 이상 데이터만 가능하므로 reshape(-1, 1)로 차원 변경
train_array = np.arange(0, 11).reshape(-1, 1)
test_array =  np.arange(0, 6).reshape(-1, 1)

* 학습 데이터인 `train_array`부터 MinMaxScaler를 이용해 변환
    * 학습 데이터는 0부터 10까지의 값을 가지는데, MinMaxScaler 객체의 `fit()`을 적용하면 최솟값 0, 최댓값 10이 설정되면 1/10 Scale이 적용됨
    * `transform()`을 호출하면 1/10 Scale로 학습 데이터를 변환하게 됨

In [12]:
# 최소값 0, 최대값 1로 변환하는 MinMaxScaler객체 생성
scaler = MinMaxScaler()
# fit()하게 되면 train_array 데이터의 최소값이 0, 최대값이 10으로 설정.  
scaler.fit(train_array)
# 1/10 scale로 train_array 데이터 변환함. 원본 10-> 1로 변환됨.
train_scaled = scaler.transform(train_array)
 
print('원본 train_array 데이터:', np.round(train_array.reshape(-1), 2))
print('Scale된 train_array 데이터:', np.round(train_scaled.reshape(-1), 2))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


* 테스트 데이터 세트를 변환할 때 `fit()`을 호출해 스케일링 기준 정보를 다시 적용한 뒤 `transform()`을 수행한 결과 확인
    * 테스트 데이터의 경우 최솟값 0, 최댓값 5이므로 1/5로 스케일링됨

In [13]:
# 앞에서 생성한 MinMaxScaler에 test_array를 fit()하게 되면 원본 데이터의 최소값이 0, 최대값이 5으로 설정됨 
scaler.fit(test_array)
# 1/5 scale로 test_array 데이터 변환함. 원본 5->1로 변환.  
test_scaled = scaler.transform(test_array)
# train_array 변환 출력
print('원본 test_array 데이터:', np.round(test_array.reshape(-1), 2))
print('Scale된 test_array 데이터:', np.round(test_scaled.reshape(-1), 2))


원본 test_array 데이터: [0 1 2 3 4 5]
Scale된 test_array 데이터: [0.  0.2 0.4 0.6 0.8 1. ]


* 이럴 경우 학습 데이터와 테스트 데이터의 서로 다른 원본값이 동일한 값으로 변환되는 결과를 초래
* 머신러닝 모델은 학습 데이터를 기반으로 학습되기 때문에 반드시 테스트 데이터는 학습 데이터의 스케일링 기준에 따라야 함
* 테스트 데이터에 다시 `fit()`을 적용해서는 안 되며 학습 데이터로 이미 `fit()`이 적용된 Scaler 객체를 이용해 `transform()`으로 변환해야 함

**테스트 데이터에 학습 데이터로 `fit()`을 수행한 MinMaxScaler 객체 적용**
* 학습 데이터, 테스트 데이터 모두 동일하게 변환됐을을 확인 가능

In [46]:
scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)
print('원본 train_array 데이터:', np.round(train_array.reshape(-1), 2))
print('Scale된 train_array 데이터:', np.round(train_scaled.reshape(-1), 2))

# test_array에 Scale 변환을 할 때는 반드시 fit()을 호출하지 않고 transform() 만으로 변환해야 함. 
test_scaled = scaler.transform(test_array)
print('\n원본 test_array 데이터:', np.round(test_array.reshape(-1), 2))
print('Scale된 test_array 데이터:', np.round(test_scaled.reshape(-1), 2))


원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

원본 test_array 데이터: [0 1 2 3 4 5]
Scale된 test_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5]


* `fit_transform()`을 적용할 때도 같음. fit_transform()은 fit()과 transform()을 순차적으로 수행하는 메소드이므로 학습 데이터에서는 상관없지만 테스트 데이터에서는 사용해서는 안됨
* 학습과 테스트 데이터에 fit()과 transform()을 적용할 때 주의 사항이 발생하므로 학습과 테스트 데이터 세트로 분리 전 먼저 전체 데이터 세트에 스케일링을 적용한 뒤 학습과 테스트 데이터 세트로 분리하는 것이 좋음

**정리**
1. 가능하다면 전체 데이터의 스케일링 변환을 적용한 뒤 학습과 테스트 데이터로 분리
2. 여의치 않다면 테스트 데이터 변환 시에는 `fit()`이나 `fit_transform()`을 적용하지 않고 핛브 데이터로 이미 `fit()`된 Scaler 객체를 이용해 `transform()`으로 변환

위 유의 사항은 PCA와 같은 차원 축소 변환 혹은 텍스트의 피처 벡터화 변환 작업 시에도 동일하게 적용됨